function [ u, v, w ] = RT2uvw( euler_angles, T )
%RT2UVW Computes the projection of the thrust in global base {A}
%   Computes the projection of the thrust generated by the quadcopter in
%    the global base {A} with the rotation matrix.
%       [u; v; w] = R(euler_angles) * [ 0; 0; T]
%
%   Inputs: euler_anlges, T
%       · euler_angles: [phi, theta, psi]
%           units: [rad]
%       · T: thrust
%           units: [N]
    
uvw = eul2rotm( euler_angles ) * [0;0;T];

u = uvw(1);
v = uvw(2);
w = uvw(3);

